
   #░██╗░░░░░░░██╗██╗██╗░░░░░██████╗░░░░░██████╗░██████╗░░█████╗░████████╗███████╗░█████╗░████████╗
   #░██║░░██╗░░██║██║██║░░░░░██╔══██╗░░░░██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██╔══██╗╚══██╔══╝
   #░╚██╗████╗██╔╝██║██║░░░░░██║░░██║░░░░██████╔╝██████╔╝██║░░██║░░░██║░░░█████╗░░██║░░╚═╝░░░██║░░░
   #░░████╔═████║░██║██║░░░░░██║░░██║░░░░██╔═══╝░██╔══██╗██║░░██║░░░██║░░░██╔══╝░░██║░░██╗░░░██║░░░
   #░░╚██╔╝░╚██╔╝░██║███████╗██████╔╝░░░░██║░░░░░██║░░██║╚█████╔╝░░░██║░░░███████╗╚█████╔╝░░░██║░░░
   #░░░╚═╝░░░╚═╝░░╚═╝╚══════╝╚═════╝░░░░░╚═╝░░░░░╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚══════╝░╚════╝░░░░╚═╝░░░
   # Made for Nontawat Matong (Facebook)

blacklist-world:
  - test1
  - test2
deny-message: "&cYou need to stay in protect stone region to place/break block!"
